"""Initial migration - create all tables

Revision ID: 4a4b423dedf7
Revises: 
Create Date: 2025-12-25 22:32:24.347946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a4b423dedf7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique code: first_word, week_streak, etc.'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Achievement title'),
    sa.Column('description', sa.Text(), nullable=False, comment='Achievement description'),
    sa.Column('icon', sa.String(length=50), nullable=False, comment='Emoji or icon name'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='vocabulary, listening, speaking, streak, general'),
    sa.Column('requirement_type', sa.String(length=50), nullable=False, comment='count, streak, score, first, etc.'),
    sa.Column('requirement_value', sa.Integer(), nullable=False, comment='Target value to unlock'),
    sa.Column('requirement_field', sa.String(length=100), nullable=True, comment='Field to check for requirement'),
    sa.Column('xp_reward', sa.Integer(), nullable=False, comment='XP awarded when unlocked'),
    sa.Column('is_hidden', sa.Boolean(), nullable=False, comment='Hidden until unlocked (secret achievements)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Display order in achievement list'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements'))
    )
    op.create_index('ix_achievement_category', 'achievements', ['category'], unique=False)
    op.create_index(op.f('ix_achievements_code'), 'achievements', ['code'], unique=True)
    op.create_table('listening_exercises',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Exercise title'),
    sa.Column('audio_url', sa.String(length=500), nullable=True, comment='URL to audio file'),
    sa.Column('transcript', sa.Text(), nullable=False, comment='Full transcript of the audio'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='Audio duration in seconds'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='clearance_delivery, ground, tower, approach, etc.'),
    sa.Column('scenario_type', sa.String(length=50), nullable=False, comment='routine, non_routine, emergency'),
    sa.Column('accent', sa.String(length=50), nullable=False, comment='American, British, Indian, etc.'),
    sa.Column('speed', sa.String(length=20), nullable=False, comment='slow, normal, fast'),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='Difficulty level 1-3'),
    sa.Column('icao_level_target', sa.Integer(), nullable=False, comment='Target ICAO level'),
    sa.Column('teaching_points', sa.JSON(), nullable=True, comment='Key learning points from this exercise'),
    sa.Column('model_readback', sa.Text(), nullable=True, comment='Example correct readback'),
    sa.Column('audio_generation_notes', sa.Text(), nullable=True, comment='Notes for audio generation'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_exercises'))
    )
    op.create_index('ix_listening_accent_speed', 'listening_exercises', ['accent', 'speed'], unique=False)
    op.create_index('ix_listening_category_difficulty', 'listening_exercises', ['category', 'difficulty'], unique=False)
    op.create_index(op.f('ix_listening_exercises_category'), 'listening_exercises', ['category'], unique=False)
    op.create_index(op.f('ix_listening_exercises_difficulty'), 'listening_exercises', ['difficulty'], unique=False)
    op.create_table('speaking_scenarios',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Scenario title'),
    sa.Column('scenario_type', sa.String(length=50), nullable=False, comment='phraseology, picture_description, conversation'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Category: phraseology, emergency, etc.'),
    sa.Column('setup', sa.Text(), nullable=False, comment='Context/situation description'),
    sa.Column('instructions', sa.Text(), nullable=True, comment='Specific instructions for the user'),
    sa.Column('atc_prompt_text', sa.Text(), nullable=False, comment='What ATC says'),
    sa.Column('atc_prompt_audio_url', sa.String(length=500), nullable=True, comment='Audio of ATC prompt'),
    sa.Column('expected_elements', sa.JSON(), nullable=True, comment='Required elements in the response'),
    sa.Column('sample_response', sa.Text(), nullable=False, comment='Example correct response'),
    sa.Column('scoring_rubric', sa.JSON(), nullable=True, comment='Rubric for each ICAO criterion'),
    sa.Column('common_cis_errors', sa.JSON(), nullable=True, comment='Common errors by CIS speakers'),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='Difficulty level 1-3'),
    sa.Column('icao_level_target', sa.Integer(), nullable=False, comment='Target ICAO level'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_scenarios'))
    )
    op.create_index('ix_scenario_difficulty', 'speaking_scenarios', ['difficulty'], unique=False)
    op.create_index('ix_scenario_type_category', 'speaking_scenarios', ['scenario_type', 'category'], unique=False)
    op.create_index(op.f('ix_speaking_scenarios_category'), 'speaking_scenarios', ['category'], unique=False)
    op.create_index(op.f('ix_speaking_scenarios_difficulty'), 'speaking_scenarios', ['difficulty'], unique=False)
    op.create_index(op.f('ix_speaking_scenarios_scenario_type'), 'speaking_scenarios', ['scenario_type'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('native_language', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('current_icao_level', sa.Integer(), nullable=True, comment="User's current/last tested ICAO level"),
    sa.Column('target_icao_level', sa.Integer(), nullable=False, comment="User's target ICAO level to achieve"),
    sa.Column('predicted_icao_level', sa.Float(), nullable=True, comment='AI-predicted ICAO level based on performance'),
    sa.Column('test_date', sa.Date(), nullable=True, comment='Scheduled ICAO test date'),
    sa.Column('test_location', sa.String(length=200), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PREMIUM', 'LIFETIME', name='subscriptiontier'), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_time', sa.String(length=5), nullable=True, comment='HH:MM format'),
    sa.Column('preferred_difficulty', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('total_practice_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_practice_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_lower', 'users', ['email'], unique=False)
    op.create_index('ix_users_subscription', 'users', ['subscription_tier'], unique=False)
    op.create_table('vocabulary_terms',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('term', sa.String(length=100), nullable=False, comment='The vocabulary term/phrase'),
    sa.Column('phonetic', sa.String(length=100), nullable=True, comment='IPA phonetic transcription'),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True, comment='noun, verb, phrase, etc.'),
    sa.Column('definition', sa.Text(), nullable=False, comment='Definition in aviation context'),
    sa.Column('aviation_context', sa.Text(), nullable=True, comment='When/how used in aviation'),
    sa.Column('example_atc', sa.Text(), nullable=True, comment='Example ATC instruction using this term'),
    sa.Column('example_response', sa.Text(), nullable=True, comment='Example pilot response'),
    sa.Column('example_sentence', sa.Text(), nullable=True, comment='General example sentence'),
    sa.Column('common_errors', sa.JSON(), nullable=True, comment='Common mistakes to avoid'),
    sa.Column('cis_pronunciation_tips', sa.Text(), nullable=True, comment='Pronunciation tips for CIS speakers'),
    sa.Column('related_terms', sa.JSON(), nullable=True, comment='Related vocabulary terms'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='standard_phraseology, weather, navigation, emergencies, etc.'),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='Difficulty level 1-5'),
    sa.Column('icao_level_target', sa.Integer(), nullable=False, comment='Target ICAO level for this term'),
    sa.Column('audio_url', sa.String(length=500), nullable=True, comment='URL to pronunciation audio'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_terms'))
    )
    op.create_index('ix_vocab_category_difficulty', 'vocabulary_terms', ['category', 'difficulty'], unique=False)
    op.create_index('ix_vocab_icao_level', 'vocabulary_terms', ['icao_level_target'], unique=False)
    op.create_index(op.f('ix_vocabulary_terms_category'), 'vocabulary_terms', ['category'], unique=False)
    op.create_index(op.f('ix_vocabulary_terms_term'), 'vocabulary_terms', ['term'], unique=False)
    op.create_table('daily_progress',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='The date for this progress record'),
    sa.Column('vocab_reviewed', sa.Integer(), nullable=False, comment='Number of vocabulary cards reviewed'),
    sa.Column('listening_completed', sa.Integer(), nullable=False, comment='Number of listening exercises completed'),
    sa.Column('speaking_completed', sa.Integer(), nullable=False, comment='Number of speaking submissions'),
    sa.Column('practice_minutes', sa.Integer(), nullable=False, comment='Total practice time in minutes'),
    sa.Column('xp_earned', sa.Integer(), nullable=False, comment='Total XP earned this day'),
    sa.Column('goal_met', sa.Boolean(), nullable=False, comment='Whether daily goal was met'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_progress')),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    op.create_index(op.f('ix_daily_progress_date'), 'daily_progress', ['date'], unique=False)
    op.create_index('ix_daily_progress_user_date', 'daily_progress', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_progress_user_id'), 'daily_progress', ['user_id'], unique=False)
    op.create_table('listening_attempts',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('exercise_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('score_percent', sa.Float(), nullable=False, comment='Score as percentage (0-100)'),
    sa.Column('answers', sa.JSON(), nullable=True, comment="User's answers: {question_id: answer}"),
    sa.Column('correct_count', sa.Integer(), nullable=False, comment='Number of correct answers'),
    sa.Column('total_questions', sa.Integer(), nullable=False, comment='Total number of questions'),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False, comment='Time spent on the exercise'),
    sa.Column('audio_plays', sa.Integer(), nullable=False, comment='Number of times audio was played'),
    sa.Column('completed', sa.Boolean(), nullable=False, comment='Whether the attempt was completed'),
    sa.Column('xp_earned', sa.Integer(), nullable=False, comment='XP earned from this attempt'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='When the attempt was completed'),
    sa.ForeignKeyConstraint(['exercise_id'], ['listening_exercises.id'], name=op.f('fk_listening_attempts_exercise_id_listening_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_listening_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_attempts'))
    )
    op.create_index('ix_attempt_user_date', 'listening_attempts', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_attempt_user_exercise', 'listening_attempts', ['user_id', 'exercise_id'], unique=False)
    op.create_index(op.f('ix_listening_attempts_exercise_id'), 'listening_attempts', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_listening_attempts_user_id'), 'listening_attempts', ['user_id'], unique=False)
    op.create_table('listening_questions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('exercise_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False, comment='multiple_choice, fill_blank, true_false'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='The question text'),
    sa.Column('options', sa.JSON(), nullable=True, comment='Options for multiple choice questions'),
    sa.Column('correct_answer', sa.String(length=500), nullable=False, comment='The correct answer'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='Explanation shown after answering'),
    sa.Column('order', sa.Integer(), nullable=False, comment='Display order within exercise'),
    sa.ForeignKeyConstraint(['exercise_id'], ['listening_exercises.id'], name=op.f('fk_listening_questions_exercise_id_listening_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_questions'))
    )
    op.create_index(op.f('ix_listening_questions_exercise_id'), 'listening_questions', ['exercise_id'], unique=False)
    op.create_index('ix_question_exercise_order', 'listening_questions', ['exercise_id', 'order'], unique=False)
    op.create_table('speaking_submissions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('scenario_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True, comment='URL to uploaded audio file'),
    sa.Column('audio_format', sa.String(length=20), nullable=True, comment='webm, m4a, mp3, wav'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='Recording duration'),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False, comment='Audio file size'),
    sa.Column('transcript', sa.Text(), nullable=True, comment='Whisper transcription of the audio'),
    sa.Column('transcript_confidence', sa.Float(), nullable=True, comment='Confidence score from Whisper'),
    sa.Column('ai_feedback', sa.JSON(), nullable=True, comment='{"strengths": [...], "improvements": [...], "overall": "..."}'),
    sa.Column('scores', sa.JSON(), nullable=True, comment='{"pronunciation": 4.2, "structure": 4.5, ...}'),
    sa.Column('score_pronunciation', sa.Float(), nullable=True),
    sa.Column('score_structure', sa.Float(), nullable=True),
    sa.Column('score_vocabulary', sa.Float(), nullable=True),
    sa.Column('score_fluency', sa.Float(), nullable=True),
    sa.Column('score_comprehension', sa.Float(), nullable=True),
    sa.Column('score_interaction', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True, comment='Overall ICAO score (1-6)'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='submissionstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if processing failed'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of processing retries'),
    sa.Column('xp_earned', sa.Integer(), nullable=False, comment='XP earned from this submission'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='When processing completed'),
    sa.ForeignKeyConstraint(['scenario_id'], ['speaking_scenarios.id'], name=op.f('fk_speaking_submissions_scenario_id_speaking_scenarios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_speaking_submissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_submissions'))
    )
    op.create_index(op.f('ix_speaking_submissions_scenario_id'), 'speaking_submissions', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_speaking_submissions_status'), 'speaking_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_speaking_submissions_user_id'), 'speaking_submissions', ['user_id'], unique=False)
    op.create_index('ix_submission_created', 'speaking_submissions', ['created_at'], unique=False)
    op.create_index('ix_submission_user_scenario', 'speaking_submissions', ['user_id', 'scenario_id'], unique=False)
    op.create_index('ix_submission_user_status', 'speaking_submissions', ['user_id', 'status'], unique=False)
    op.create_table('streaks',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False, comment='Current consecutive days streak'),
    sa.Column('longest_streak', sa.Integer(), nullable=False, comment='Longest streak ever achieved'),
    sa.Column('last_practice_date', sa.Date(), nullable=True, comment='Date of last practice'),
    sa.Column('freeze_available', sa.Integer(), nullable=False, comment='Number of streak freezes available'),
    sa.Column('freeze_used_date', sa.Date(), nullable=True, comment='Date when freeze was last used'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_streaks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_streaks'))
    )
    op.create_index(op.f('ix_streaks_user_id'), 'streaks', ['user_id'], unique=True)
    op.create_table('user_achievements',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('achievement_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False, comment='Progress toward achievement (for incremental)'),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True, comment='When the achievement was unlocked (null if not yet)'),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False, comment='Whether achievement is unlocked'),
    sa.Column('notified', sa.Boolean(), nullable=False, comment='Whether user has been notified of unlock'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_user_achievements_achievement_id_achievements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_achievements')),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index('ix_user_achievement_date', 'user_achievements', ['unlocked_at'], unique=False)
    op.create_index('ix_user_achievement_user', 'user_achievements', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('vocabulary_progress',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('term_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False, comment='Ease factor (min 1.3, default 2.5)'),
    sa.Column('interval_days', sa.Integer(), nullable=False, comment='Current interval in days'),
    sa.Column('repetitions', sa.Integer(), nullable=False, comment='Consecutive correct reviews'),
    sa.Column('next_review_at', sa.DateTime(), nullable=False, comment='When this card is due for review'),
    sa.Column('total_reviews', sa.Integer(), nullable=False, comment='Total number of reviews'),
    sa.Column('correct_reviews', sa.Integer(), nullable=False, comment='Number of correct reviews (quality >= 3)'),
    sa.Column('last_quality', sa.Integer(), nullable=True, comment='Last review quality rating (0-5)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True, comment='When the term was last reviewed'),
    sa.ForeignKeyConstraint(['term_id'], ['vocabulary_terms.id'], name=op.f('fk_vocabulary_progress_term_id_vocabulary_terms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vocabulary_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_progress')),
    sa.UniqueConstraint('user_id', 'term_id', name='uq_user_term')
    )
    op.create_index('ix_vocab_progress_review', 'vocabulary_progress', ['user_id', 'next_review_at'], unique=False)
    op.create_index(op.f('ix_vocabulary_progress_next_review_at'), 'vocabulary_progress', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_vocabulary_progress_term_id'), 'vocabulary_progress', ['term_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_progress_user_id'), 'vocabulary_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_progress_user_id'), table_name='vocabulary_progress')
    op.drop_index(op.f('ix_vocabulary_progress_term_id'), table_name='vocabulary_progress')
    op.drop_index(op.f('ix_vocabulary_progress_next_review_at'), table_name='vocabulary_progress')
    op.drop_index('ix_vocab_progress_review', table_name='vocabulary_progress')
    op.drop_table('vocabulary_progress')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_index('ix_user_achievement_user', table_name='user_achievements')
    op.drop_index('ix_user_achievement_date', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_streaks_user_id'), table_name='streaks')
    op.drop_table('streaks')
    op.drop_index('ix_submission_user_status', table_name='speaking_submissions')
    op.drop_index('ix_submission_user_scenario', table_name='speaking_submissions')
    op.drop_index('ix_submission_created', table_name='speaking_submissions')
    op.drop_index(op.f('ix_speaking_submissions_user_id'), table_name='speaking_submissions')
    op.drop_index(op.f('ix_speaking_submissions_status'), table_name='speaking_submissions')
    op.drop_index(op.f('ix_speaking_submissions_scenario_id'), table_name='speaking_submissions')
    op.drop_table('speaking_submissions')
    op.drop_index('ix_question_exercise_order', table_name='listening_questions')
    op.drop_index(op.f('ix_listening_questions_exercise_id'), table_name='listening_questions')
    op.drop_table('listening_questions')
    op.drop_index(op.f('ix_listening_attempts_user_id'), table_name='listening_attempts')
    op.drop_index(op.f('ix_listening_attempts_exercise_id'), table_name='listening_attempts')
    op.drop_index('ix_attempt_user_exercise', table_name='listening_attempts')
    op.drop_index('ix_attempt_user_date', table_name='listening_attempts')
    op.drop_table('listening_attempts')
    op.drop_index(op.f('ix_daily_progress_user_id'), table_name='daily_progress')
    op.drop_index('ix_daily_progress_user_date', table_name='daily_progress')
    op.drop_index(op.f('ix_daily_progress_date'), table_name='daily_progress')
    op.drop_table('daily_progress')
    op.drop_index(op.f('ix_vocabulary_terms_term'), table_name='vocabulary_terms')
    op.drop_index(op.f('ix_vocabulary_terms_category'), table_name='vocabulary_terms')
    op.drop_index('ix_vocab_icao_level', table_name='vocabulary_terms')
    op.drop_index('ix_vocab_category_difficulty', table_name='vocabulary_terms')
    op.drop_table('vocabulary_terms')
    op.drop_index('ix_users_subscription', table_name='users')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_speaking_scenarios_scenario_type'), table_name='speaking_scenarios')
    op.drop_index(op.f('ix_speaking_scenarios_difficulty'), table_name='speaking_scenarios')
    op.drop_index(op.f('ix_speaking_scenarios_category'), table_name='speaking_scenarios')
    op.drop_index('ix_scenario_type_category', table_name='speaking_scenarios')
    op.drop_index('ix_scenario_difficulty', table_name='speaking_scenarios')
    op.drop_table('speaking_scenarios')
    op.drop_index(op.f('ix_listening_exercises_difficulty'), table_name='listening_exercises')
    op.drop_index(op.f('ix_listening_exercises_category'), table_name='listening_exercises')
    op.drop_index('ix_listening_category_difficulty', table_name='listening_exercises')
    op.drop_index('ix_listening_accent_speed', table_name='listening_exercises')
    op.drop_table('listening_exercises')
    op.drop_index(op.f('ix_achievements_code'), table_name='achievements')
    op.drop_index('ix_achievement_category', table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
